//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EN_project.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities11 : DbContext
    {
        public DBEntities11()
            : base("name=DBEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departmebt> Departmebts { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<StudentMark> StudentMarks { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<SubjectLecture> SubjectLectures { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
    }
}
