//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EN_project.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subject()
        {
            this.Exams = new HashSet<Exam>();
            this.SubjectLectures = new HashSet<SubjectLecture>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Departmentld { get; set; }
        public string Name { get; set; }
        public Nullable<int> MlnimumDegree { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Departmebt Departmebt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectLecture> SubjectLectures { get; set; }
    }
}
